// client/angular-web/src/app/components/actions/add-transaction/add-transaction.component.ts
import { Component, inject } from '@angular/core';
import { CategorySelectComponent } from '../../selects/category-select/category-select.component';
import { BusinessSelectComponent } from '../../selects/business-select/business-select.component';
import {
  FormBuilder,
  FormGroup,
  Validators,
  ReactiveFormsModule,
} from '@angular/forms';
import ApiProvider from '../../../../services/api.service';
import AuthService from '../../../../services/auth.service';
import ProfileDataService from '../../../../services/profileData.service';

@Component({
  selector: 'app-add-transaction',
  imports: [
    CategorySelectComponent,
    BusinessSelectComponent,
    ReactiveFormsModule,
  ],
  templateUrl: './add-transaction.component.html',
  styleUrl: './add-transaction.component.css',
})
export class AddTransactionComponent {
  selectedCategory: string = '';
  selectedBusiness: string = '';
  private fb = inject(FormBuilder);
  private api = inject(ApiProvider);
  private auth = inject(AuthService);
  private pData = inject(ProfileDataService);
  addTransactionForm: FormGroup;

  constructor() {
    this.addTransactionForm = this.fb.group({
      amount: [0, [Validators.required, Validators.min(0)]],
      date: ['', [Validators.required]],
      description: [''],
    });
  }

  setCategory(category: string) {
    this.selectedCategory = category;
  }

  setBusiness(bussiness: string) {
    this.selectedBusiness = bussiness;
  }

  addTransaction() {
    const { amount, date, description } = this.addTransactionForm.value;
    const payload = {
      refId: this.auth.getProfile()?.expenses,
      catName: this.selectedCategory,
      busName: this.selectedBusiness,
      transaction: {
        amount: Number(amount),
        date: new Date(date).toISOString(),
        description,
      },
    };
    this.api.post('expenses/transaction/create', payload).subscribe({
      next: (response) => {
        console.log('success');
        this.pData.fetchAllData();
      },
      error(err) {
        console.log('server error');
      },
    });
  }
}

<div class="grid">
  <app-category-select (onChange)="setCategory($event)"></app-category-select>
  @if (selectedCategory) {
    <app-business-select
      [selectedCategory]="selectedCategory"
      (onChange)="setBusiness($event)"
    ></app-business-select>
    @if (selectedBusiness) {
      <form class="grid" [formGroup]="addTransactionForm" (submit)="addTransaction()">
        <label for="">סכום</label>
        <input type="number" 
        formControlName="amount"/>
        <label for="">תאריך</label>
        <input formControlName="date"
         type="date" />
        <label for="">תיאור(אופציונלי)</label>
        <input formControlName="description"
        type="text" />
        <button type="submit" [disabled]="!addTransactionForm.valid">הוסף עסקה</button>
      </form>
    }
  }
</div>

// client/New folder/components/dashboard/expenses/transactions/AddTransaction.jsx
import { useState } from "react";
import { useAuth } from "../../../../context/AuthContext";
import CategorySelect from "../categories/CategorySelect";
import BusinessSelect from "../businesses/BusinessSelect";
import { post } from "../../../../utils/api";

export default function AddTransaction({ goBack }) {
    const { profile } = useAuth();
    const [selectedCategory, setSelectedCategory] = useState(null);
    const [selectedBusiness, setSelectedBusiness] = useState(null);
    const [amount, setAmount] = useState(null);
    const [date, setDate] = useState(null);
    const [description, setDescription] = useState('');
    const [error, setError] = useState(null);
    const [success, setSuccess] = useState(null);

    const addTransaction = async (e) => {
        e.preventDefault();
        console.log('Adding transaction:', {
            selectedCategory,
            selectedBusiness,
            amount,
            date,
            description
        });
        if (!selectedCategory || !selectedBusiness || !amount || !date) {
            setError('אנא מלא את כל השדות');
            return;
        }
        const transaction = {
            amount: amount,
            date: new Date(date),
            description: description
        }

        const response = await post('expenses/create-transaction', {
            refId: profile.expenses,
            catName: selectedCategory,
            busName: selectedBusiness,
            transaction
        });

        console.log(response);

    }

    return (
        <form onSubmit={addTransaction}>

            <CategorySelect refId={profile.expenses} setSelectedCategory={setSelectedCategory} />
            {selectedCategory && <BusinessSelect refId={profile.expenses} category={selectedCategory} setSelectedBusiness={setSelectedBusiness} />}
            {selectedBusiness && (
                <>
                    <input type="number" name="amount" id="amount" placeholder="סכום" onChange={(e) => setAmount(e.target.value)} />
                    <label htmlFor="date">בחר תאריך</label>
                    <input type="date" name="date" id="date" onChange={(e) => setDate(e.target.value)} />
                    <input type="text" name="description" id="description" placeholder="תיאור" onChange={(e) => setDescription(e.target.value)} />
                    <input type="submit" value="הוסף הוצאה" />
                </>
            )}
            <input type="button" value="חזור" onClick={goBack} />
        </form>
    );
}
