// client/angular-web/src/app/components/profile/create-profile/create-profile.component.ts
import { Component, inject, Input } from '@angular/core';
import { Account } from '../../../../types';
import { ColorPickerComponent } from '../../color-picker/color-picker.component';
import {
  FormBuilder,
  FormGroup,
  ReactiveFormsModule,
  Validators,
} from '@angular/forms';
import ApiProvider from '../../../../services/api.service';

type NewProfilePayload = {
  username: string;
  profileName: string;
  pin: string;
  avatar: string | null;
  color: string | null;
  parentProfile: boolean;
};

@Component({
  selector: 'app-create-profile',
  imports: [ColorPickerComponent, ReactiveFormsModule],
  templateUrl: './create-profile.component.html',
  styleUrl: './create-profile.component.css',
})
export class CreateProfileComponent {
  @Input() account: Account | null = null;
  @Input() firstProfile: boolean = false;
  fb: FormBuilder = inject(FormBuilder);
  api: ApiProvider = inject(ApiProvider);
  profileForm: FormGroup;
  color: string | null = null;
  avatarFile: File | null = null;

  constructor() {
    this.profileForm = this.fb.group({
      profileName: ['', [Validators.required, Validators.minLength(2)]],
      pin: [
        '',
        [Validators.required, Validators.minLength(4), Validators.maxLength(4)],
      ],
      parentProfile: [this.firstProfile],
    });
  }

  onColorClick(c: string) {
    this.color = c;
  }

  onAvatarPick(event: Event) {
    const input = event.target as HTMLInputElement;
    if (!input.files || !(input.files.length > 0)) {
      return;
    }
    this.avatarFile = input.files[0];
  }

  async onSubmit() {
    if (!this.account) {
      return;
    }
    let { profileName, pin, parentProfile } = this.profileForm.value;
    let avatar: string | null = null;
    if (this.avatarFile) {
      avatar = await this.prepareImage(this.avatarFile);
    }
    parentProfile = this.firstProfile ? true : parentProfile;
    const payload: NewProfilePayload = {
      username: this.account.username,
      profileName,
      pin,
      parentProfile: this.firstProfile ? true : parentProfile,
      avatar,
      color: this.color,
    };
    const uri = this.firstProfile
      ? 'create-first-profile'
      : parentProfile
        ? 'create-profile'
        : 'create-child-profile';
    this.api.post(`profile/${uri}`, payload).subscribe({
      next: (response) => {
        if (response.ok) {
          window.location.reload();
        }
      },
      error: (err) => {
        //TODO
        console.log('handle error');
      },
    });
  }

  private prepareImage(file: File): Promise<string> {
    return new Promise((resolve, reject) => {
      const reader = new FileReader();
      reader.onload = () => resolve(reader.result as string);
      reader.onerror = reject;
      reader.readAsDataURL(file);
    });
  }
}

<form [formGroup]="profileForm" class="grid" (submit)="onSubmit()">
  <label for="profileName">שם פרופיל</label>
  <input type="text" formControlName="profileName" />
  <label for="pin">קוד סודי</label>
  <input type="password" name="pin" formControlName="pin" maxlength="4"/>
  <label for="avatar">תמונת פרופיל</label>
  <input type="file" name="avatar" (change)="onAvatarPick($event)" />
  <app-color-picker (setProfileColor)="onColorClick($event)"></app-color-picker>
  <label for="parentProfile">פרופיל הורה</label>
  @if (!firstProfile) {
    <input
      type="checkbox"
      name="parentProfile"
      formControlName="parentProfile"
    />
  }
  <button [disabled]="!profileForm.valid" type="submit">צור פרופיל חדש</button>
</form>

// client/web/src/components/profile/CreateProfile.jsx
import { useState } from 'react';
import { post } from '../../utils/api';

const toBase64 = async (file) => {
    return new Promise((resolve, reject) => {
        const reader = new FileReader();
        reader.readAsDataURL(file);
        reader.onload = () => resolve(reader.result);
        reader.onerror = error => reject(error);
    });
}

export default function CreateProfile({ username, firstProfile, onProfileCreated }) {

    const [profileName, setProfileName] = useState('');
    const [avatar, setAvatar] = useState(null);
    const [color, setColor] = useState('#000000');
    const [pin, setPin] = useState('');
    const [parentProfile, setParentProfile] = useState(false);
    const [error, setError] = useState('');

    const createProfile = async (e) => {
        e.preventDefault();
        if (!profileName || !pin || profileName.trim() === '' || pin.trim() === '') {
            setError('Profile name and PIN are required.');
            return;
        }
        setError('');
        let avatarBase64 = null;
        if (avatar) {
            try {
                avatarBase64 = await toBase64(avatar);
            } catch (error) {
                setError('Failed to upload avatar.');
                return;
            }
        }
        const newProfile = {
            username,
            profileName,
            pin,
            avatar: avatar ? avatarBase64 : null,
            color,
            parentProfile: firstProfile || parentProfile,
        }

        const uri = parentProfile ? "create-profile" : "create-child-profile";

        const response = await post(`profile/${uri}`, newProfile);

        if (response.ok) {
            if (firstProfile) {
                window.location.reload();
            } else if (onProfileCreated) {
                setProfileName('');
                setPin('');
                setAvatar(null);
                setColor('#000000');
                setParentProfile(false);
                onProfileCreated();
            }
        } else {
            setError(response.message || 'Failed to create profile.');
        }
    };

    return (
        <div className="w-full max-w-md mx-auto" dir="rtl">
            <div className="p-8 space-y-6 bg-white rounded-lg shadow-md">
                <h2 className="text-2xl font-bold text-center text-gray-900">הוספת פרופיל</h2>
                {error && <p className="text-sm text-center text-red-600 bg-red-100 border border-red-400 rounded-md py-2 px-4">{error}</p>}
                <form onSubmit={createProfile} className="space-y-6">
                    <div>
                        <label className="block text-sm font-medium text-gray-700 mb-1">שם פרופיל</label>
                        <input
                            type="text"
                            className="w-full px-4 py-2 text-right border border-gray-300 rounded-md shadow-sm focus:outline-none focus:ring-2 focus:ring-indigo-500 focus:border-indigo-500"
                            placeholder="הכנס שם פרופיל"
                            onChange={(e) => setProfileName(e.target.value)}
                        />
                    </div>
                    <div>
                        <label className="block text-sm font-medium text-gray-700 mb-1">קוד סודי</label>
                        <input
                            type="password"
                            className="w-full px-4 py-2 text-right border border-gray-300 rounded-md shadow-sm focus:outline-none focus:ring-2 focus:ring-indigo-500 focus:border-indigo-500"
                            placeholder="הכנס קוד סודי (4 ספרות)"
                            onChange={(e) => setPin(e.target.value)}
                            maxLength="4"
                        />
                    </div>
                    <div>
                        <label className="block text-sm font-medium text-gray-700 mb-1">הוסף תמונת פרופיל</label>
                        <div className="flex items-center gap-4">
                            <label
                                htmlFor="avatar-upload"
                                className="w-full cursor-pointer bg-white py-2 px-3 border border-gray-300 rounded-md shadow-sm text-sm font-medium text-gray-700 hover:bg-gray-50"
                            >
                                <span>בחר קובץ</span>
                            </label>
                            <input
                                id="avatar-upload"
                                type="file"
                                className="hidden"
                                accept="image/*"
                                onChange={(e) => setAvatar(e.target.files[0])}
                            />
                            {avatar && <span className="text-sm text-gray-500">{avatar.name}</span>}
                        </div>
                    </div>
                    <div>
                        <label className="block text-sm font-medium text-gray-700 mb-1">בחר צבע</label>
                        <input
                            type="color"
                            className="w-full h-10 p-1 border border-gray-300 rounded-md"
                            onChange={(e) => setColor(e.target.value)}
                        />
                    </div>
                    {!firstProfile && (
                        <div className="flex items-center gap-2">
                            <input
                                type="checkbox"
                                className="w-4 h-4 text-indigo-600 border-gray-300 rounded focus:ring-indigo-500"
                                checked={parentProfile}
                                onChange={(e) => setParentProfile(e.target.checked)}
                            />
                            <label className="text-sm text-gray-900">הגדר כפרופיל הורה</label>
                        </div>
                    )}
                    <button
                        className="w-full py-2 px-4 font-semibold text-white bg-indigo-600 rounded-md shadow-md hover:bg-indigo-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500 disabled:bg-gray-400 disabled:cursor-not-allowed"
                        type="submit"
                    >
                        צור פרופיל
                    </button>
                </form>
            </div>
        </div>
    );
}
